version: '3.7'

services:
  psql12:
    # image: postgres:12.4-alpine
    build: ./docker/postgres
    container_name: org-sql-postgres-12
    restart: 'no'
    environment:    
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
    ports:
      - 60000:5432

  postgrest:
    build:
      context: ./docker/postgrest
      args:
        POSTGREST_VERSION: "7.0.1"
    environment:
      - PGRST_DB_URI=postgres://authenticator:authenticator@psql12:5432/org_sql
      - PGRST_DB_SCHEMA=restapi
      - PGRST_DB_ANON_ROLE=web_anon
      - PGRST_JWT_SECRET=abcdefghijklmnopqrstuvwxyz1234567890
    ports:
      - 60010:3000
    depends_on:
      - psql12

  # mariadb10:
  #   image: mariadb:10.5.8
  #   container_name: org-sql-mariadb-10
  #   restart: 'no'
  #   environment:    
  #     - MYSQL_ROOT_PASSWORD=toor
  #     - MYSQL_USER=org_sql
  #     - MYSQL_PASSWORD=org_sql
  #     - MYSQL_DATABASE=org_sql
  #   ports:
  #     - 60100:3306

  # mysql5:
  #   image: mysql:5.6.51
  #   container_name: org-sql-mysql-5
  #   restart: 'no'
  #   environment:    
  #     - MYSQL_ROOT_PASSWORD=toor
  #     - MYSQL_USER=org_sql
  #     - MYSQL_PASSWORD=org_sql
  #     - MYSQL_DATABASE=org_sql
  #   ports:
  #     - 60200:3306

  # sqlserver2019:
  #   build: ./docker/sql-server
  #   container_name: org-sql-sqlserver-2019
  #   restart: 'no'
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=org_sql222@@@
  #   ports:
  #     - 60300:1433
