version: '3.7'

services:
  psql12:
    build: ./test/docker/postgres
    container_name: org-sql-postgres-12
    restart: 'no'
    environment:    
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
    ports:
      - 60000:5432

  mariadb10:
    image: mariadb:10.5.8
    container_name: org-sql-mariadb-10
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    ports:
      - 60100:3306

  mysql5:
    image: mysql:5.6.51
    container_name: org-sql-mysql-5
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    ports:
      - 60200:3306

  sqlserver2019:
    build: ./test/docker/sql-server
    container_name: org-sql-sqlserver-2019
    restart: 'no'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=org_sql222@@@
    ports:
      - 60300:1433
