version: '3.7'

services:
  psql:
    image: postgres:12.4-alpine
    container_name: org-sql-postgres
    restart: 'no'
    environment:    
      - POSTGRES_PASSWORD=org_sql
      - POSTGRES_USER=org_sql
    ports:
      - 60000:5432
  mariadb:
    image: mariadb:10.5.8
    container_name: org-sql-mariadb
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    ports:
      - 60100:3306
  mysql:
    image: mysql:5.6.51
    container_name: org-sql-mysql
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    ports:
      - 60200:3306
  sqlserver:
    build: ./docker/sql-server
    container_name: org-sql-sqlserver
    restart: 'no'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=org_sql222@@@
    ports:
      - 60300:1433
