version: '3.7'

services:
  psql-latest:
    build: ./test/docker/postgres
    container_name: org-sql-postgres-latest
    restart: 'no'
    environment:    
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
    # ports:
    #   - 60000:5432

  mariadb-latest:
    image: mariadb:10.5.8
    container_name: org-sql-mariadb-latest
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    # ports:
    #   - 60100:3306

  mysql-latest:
    image: mysql:8.0.23
    container_name: org-sql-mysql-latest
    restart: 'no'
    environment:    
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=org_sql
      - MYSQL_PASSWORD=org_sql
      - MYSQL_DATABASE=org_sql
    # ports:
    #   - 60200:3306

  sqlserver-latest:
    build: ./test/docker/sql-server
    container_name: org-sql-sqlserver-latest
    restart: 'no'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=org_sql222@@@
    # ports:
    #   - 60300:1433
