name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '27.1'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
      with:
        version: '0.8.4'

    - name: Setup testing databases
      run: docker-compose up -d

    - name: Run tests
      if: matrix.allow_failure != true
      run: |
        cask install
        make

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: |
        cask install
        make || true
